services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ef_squad_finder_db_container
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "password1234$"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data: