name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore Dependencies
      run: dotnet restore EplSquadFinder.sln

    - name: Build API
      run: dotnet build EplSquadFinder.Api/EplSquadFinder.Api.csproj --configuration Release --no-restore
