name: Build & Test & Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore Dependencies
      run: dotnet restore epl-squad-finder-api/EplSquadFinder.sln

    - name: Build API
      run: dotnet build epl-squad-finder-api/EplSquadFinder.Api/EplSquadFinder.Api.csproj --configuration Release --no-restore

    - name: Run Tests
      run: dotnet test epl-squad-finder-api/tests/EplSquadFinder.Application.Tests/EplSquadFinder.Application.Tests.csproj --configuration Release --no-restore

  build_and_push:
    needs: build_and_test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build and push API image
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/epl-squad-finder-api:latest -f epl-squad-finder-api/EplSquadFinder.Api/Dockerfile .
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/epl-squad-finder-api:latest

      - name: Build and push UI image
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/epl-squad-finder-ui:latest -f epl-squad-finder-ui/Dockerfile .
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/epl-squad-finder-ui:latest